src/HS.EndPoints.RazorPages.ShopUI/Areas/Admin/Pages/AccessDenied.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HS.EndPoints.RazorPages.UI.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Admin/Pages/Comment.cshtml.cs
using AutoMapper;
using HS.Domain.Core.Contracts.ApplicationService;
using HS.EndPoints.RazorPages.UI.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HS.EndPoints.RazorPages.UI.Areas.Admin.Pages
{
     
    public class CommentModel : PageModel
    {
        private readonly ICommentApplicationService _commentApplicationService;
        public List<CommentViewModel> comments;

        private readonly IMapper _mapper;

        public CommentModel(ICommentApplicationService commentApplicationService,
            IMapper mapper)
        {
            _commentApplicationService = commentApplicationService;
            _mapper = mapper;
        }

        public async Task OnGet(CancellationToken cancellationToken)
        {

            var records = await _commentApplicationService.GetAll(cancellationToken);
            comments = _mapper.Map(records, comments);
        }

        public async Task<IActionResult> OnPostActive(int commentId,CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
                await _commentApplicationService.Active(commentId, cancellationToken);
                return LocalRedirect("/Admin/comment");
        }

        public async Task<IActionResult> OnPostDeActive(int commentId,CancellationToken cancellationToken)
        {
            if(ModelState.IsValid)
            await _commentApplicationService.DeActive(commentId,cancellationToken);
            return LocalRedirect("/Admin/comment");
        }
    }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Admin/Pages/ExpertComment.cshtml.cs
using AutoMapper;
using HS.Domain.Core.Contracts.ApplicationService;
using HS.EndPoints.RazorPages.UI.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HS.EndPoints.RazorPages.UI.Areas.Admin.Pages
{
    [Authorize(Roles = "Admin,Customer")]
    public class ExpertCommentModel : PageModel
    {

        private readonly ICommentApplicationService _commentApplicationService;
        public List<CommentViewModel> comments;
        private readonly IMapper _mapper;

        public ExpertCommentModel(ICommentApplicationService commentApplicationService,
            IMapper mapper)
        {
            _commentApplicationService = commentApplicationService;
            _mapper = mapper;
        }

        public async Task OnGet(Guid ExpertId,CancellationToken cancellationToken)
        {
            var result = await _commentApplicationService.GetBy(ExpertId, cancellationToken);
            comments =  _mapper.Map(result, comments);
            
        }
    }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Admin/Pages/HomeServices.cshtml.cs
using AutoMapper;
using HS.Domain.ApplicationServices;
using HS.Domain.Core.Contracts.ApplicationService;
using HS.Domain.Core.Dtos;
using HS.Domain.Core.Entities;
using HS.EndPoints.RazorPages.UI.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HS.EndPoints.RazorPages.UI.Areas.Admin.Pages
{
    public class HomeServicesModel : PageModel
    {
        private readonly IHomeServiceApplicationService _homeServiceApplicationService;
        private readonly IHomeServiceSubCategoryApplicationService _homeServiceSubCategoryApplicationService;
        private readonly IMapper _mapper;

        public HomeServicesModel(IHomeServiceApplicationService homeServiceApplicationService,
            IHomeServiceSubCategoryApplicationService homeServiceSubCategoryApplicationService,
            IMapper mapper)
        {
            _homeServiceApplicationService = homeServiceApplicationService;
            _homeServiceSubCategoryApplicationService = homeServiceSubCategoryApplicationService;
            _mapper = mapper;
        }

        public List<HomeServiceViewModel> HomeServices { get; set; }
        public SelectList  homeServiceSubCategories { get; set; }


        public async Task OnGet(CancellationToken cancellationToken)
        {
            HomeServices = _mapper.Map(await _homeServiceApplicationService.Get(cancellationToken) , new List<HomeServiceViewModel>()) ;
            homeServiceSubCategories = new SelectList(await _homeServiceSubCategoryApplicationService.GetAll(cancellationToken), "Id", "Name");
        }

        public async Task<IActionResult> OnPostCreate(HomeServiceViewModel model,CancellationToken cancellationToken)
        {
            await _homeServiceApplicationService.Create(_mapper.Map(model,new HomeServiceDto()), cancellationToken);
            return LocalRedirect("/Admin/HomeServices");
        }

        public async Task<IActionResult> OnPostActive(int id,CancellationToken cancellationToken)
        {
            await _homeServiceApplicationService.Active(id, cancellationToken);
            return LocalRedirect("/Admin/HomeServices");
        }
        public async Task<IActionResult> OnPostDeActive(int id,CancellationToken cancellationToken)
        {
            await _homeServiceApplicationService.DeActive(id, cancellationToken);
            return LocalRedirect("/Admin/HomeServices");
        }
    }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Admin/Pages/Index.cshtml.cs
using AutoMapper;
using HS.Domain.Core.Contracts.ApplicationService;
using HS.EndPoints.RazorPages.UI.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;

namespace HS.EndPoints.RazorPages.ShopUI.Areas.Admin.Pages
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IExpertApplicationService _expertApplicationService;
        private readonly ICustomerApplicationService _customerApplicationService;
        private readonly IOrderApplicationService _orderApplicationService;
        private readonly ISuggestionApplicationService _suggestionApplicationService;
        private readonly IMemoryCache _memoryCache;


        private readonly IMapper _mapper;

        public DashboardViewModel dashboardViewModel { get; set; } = new DashboardViewModel();
        public ICollection<OrderViewModel>? Orders = new List<OrderViewModel>();
        public ICollection<SuggestionViewModel> suggestions = new List<SuggestionViewModel>();
        public int onlineUser;
        public IndexModel(IExpertApplicationService expertApplicationService,
            ICustomerApplicationService customerApplicationService,
            IOrderApplicationService orderApplicationService,
            ISuggestionApplicationService suggestionApplicationService,
            IMapper mapper,
            IMemoryCache memoryCache)
        {
            _expertApplicationService = expertApplicationService;
            _customerApplicationService = customerApplicationService;
            _orderApplicationService = orderApplicationService;
            _suggestionApplicationService = suggestionApplicationService;
            _mapper = mapper;
            _memoryCache = memoryCache;
        }

        public async Task OnGet(CancellationToken cancellationToken)
        {
            dashboardViewModel.CountExpert = await _expertApplicationService.Count(cancellationToken);
            dashboardViewModel.CountCustomer = await _customerApplicationService.Count(cancellationToken);
            dashboardViewModel.CountOrder = await _orderApplicationService.Count(cancellationToken);
            dashboardViewModel.CountSuggestion = await _suggestionApplicationService.Count(cancellationToken);
            Orders = _mapper.Map(await _orderApplicationService.GetAll(cancellationToken), Orders);
            suggestions = _mapper.Map(await _suggestionApplicationService.Get(cancellationToken),new List<SuggestionViewModel>());
        }
    }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Admin/Pages/OrderDetails.cshtml.cs
using HS.Domain.Core.Contracts.ApplicationService;
using Microsoft.AspNetCore.Mvc.RazorPages;
using HS.EndPoints.RazorPages.UI.Model;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;

namespace HS.EndPoints.RazorPages.UI.Areas.Admin.Pages
{
    [Authorize]
    public class OrderDetailsModel : PageModel
    {
        private readonly ISuggestionApplicationService _suggestionApplicationService;
        private readonly IOrderFileApplicationService _orderFileApplicationService;
        private readonly ICommentApplicationService _commentApplicationService;
        private readonly IExpertApplicationService _expertApplicationService;
        private readonly IOrderApplicationService _orderApplicationService;
        public ICollection<SuggestionViewModel> suggestions = new List<SuggestionViewModel>();
        public ICollection<OrderFileViewModel> orderFiles = new List<OrderFileViewModel>();
        public string currentUserID { get; set; } = string.Empty;
        public OrderViewModel Order = new OrderViewModel();
        private readonly IMapper _mapper;
        public Guid UserId;
        
        public OrderDetailsModel(ISuggestionApplicationService suggestionApplicationService,
            ICommentApplicationService commentApplicationService,
            IOrderFileApplicationService orderFileApplicationService,
            IExpertApplicationService expertApplicationService,
            IOrderApplicationService orderApplicationService,
            IMapper mapper)
        {
            _suggestionApplicationService = suggestionApplicationService;
            _orderFileApplicationService = orderFileApplicationService;
            _commentApplicationService = commentApplicationService;
            _expertApplicationService = expertApplicationService;
            _orderApplicationService = orderApplicationService;
            _mapper = mapper;
        }

        public async Task OnGet(int OrderId,CancellationToken cancellationToken)
        {

            _mapper.Map(await _orderApplicationService.GetBy(OrderId, cancellationToken), Order);
            _mapper.Map(await _suggestionApplicationService.GetAll(OrderId, cancellationToken), suggestions);
            _mapper.Map(await _orderFileApplicationService.GetAll(OrderId, cancellationToken), orderFiles);
            if (User.IsInRole("Expert"))
            UserId = await _expertApplicationService.GetExpertId(cancellationToken);
        }

        public async Task<IActionResult> OnPostDeleteImage(int imageId , int orderIdDelete,CancellationToken cancellationToken)
        {
            if(ModelState.IsValid)
                await _orderFileApplicationService.DeleteFile(imageId, cancellationToken);
                return RedirectToPage("/OrderDetails", new { OrderId = orderIdDelete });

        }

        public async Task<IActionResult> OnPostComment(string Comment,int OrderId,CancellationToken cancellationToken)
        {
            await _commentApplicationService.Create(Comment, OrderId,cancellationToken);
            return RedirectToPage("/OrderDetails", new { OrderId });
        }

        public async Task<IActionResult> OnPostAccept(int SuggId, int OrderId,CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
                await _suggestionApplicationService.Accept(SuggId, OrderId, cancellationToken);
            return LocalRedirect("/Admin/Order/");
        }
    }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Admin/Pages/Profile.cshtml.cs
using HS.Domain.Core.Contracts.ApplicationService;
using HS.EndPoints.RazorPages.ShopUI.Model;
using Microsoft.AspNetCore.Mvc.RazorPages;
using HS.Domain.Core.Contracts.Repository;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using HS.Domain.Core.Entities;
using System.Security.Claims;
using HS.Domain.Core.Dtos;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;

namespace HS.EndPoints.RazorPages.UI.Areas.Admin.Pages
{
    [Authorize]
    public class ProfileModel : PageModel
    {
        private readonly IApplicationUserApplicationService _userApplicationService;

        public UserViewModel UserViewModel = new UserViewModel();
        private readonly IMapper _mapper;


        public ProfileModel(IMapper mapper,IApplicationUserApplicationService userApplicationService)
        {
            _mapper = mapper;
            _userApplicationService = userApplicationService;
        }

        public async Task<IActionResult> OnPost(UserViewModel model,CancellationToken cancellationToken)
        {
            await _userApplicationService.Update(_mapper.Map(model, new UserDto()), cancellationToken);
            return LocalRedirect("/Admin/Profile/");
        }

        public async Task OnGet(CancellationToken cancellationToken)
        {
            UserViewModel = _mapper.Map(await _userApplicationService.Get(cancellationToken), UserViewModel);
        }
    }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Admin/Pages/Suggestions.cshtml.cs
using HS.Domain.Core.Contracts.ApplicationService;
using Microsoft.AspNetCore.Mvc.RazorPages;
using HS.EndPoints.RazorPages.UI.Model;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;

namespace HS.EndPoints.RazorPages.UI.Areas.Admin.Pages
{
    [Authorize(Roles = "Admin,Customer")]
    public class SuggestionsModel : PageModel
    {
        public ICollection<SuggestionViewModel> suggestions = new List<SuggestionViewModel>();
        private readonly ISuggestionApplicationService _suggestionApplicationService;
        private readonly IMapper _mapper;

        public SuggestionsModel(ISuggestionApplicationService suggestionApplicationService,
            IMapper mapper)
        {
            _suggestionApplicationService = suggestionApplicationService;
            _mapper = mapper;
        }

        public async Task OnGet(int orderId,CancellationToken cancellationToken)
        {
            if(ModelState.IsValid)
            _mapper.Map(await _suggestionApplicationService.GetAll(orderId, cancellationToken),suggestions);
        }

        public async Task<IActionResult> OnPostAccept(int SuggId , int OrderId, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
                await _suggestionApplicationService.Accept(SuggId, OrderId, cancellationToken);
            return LocalRedirect("/Admin/Order/");
        }

    }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Admin/Pages/UserManagement.cshtml.cs
using AutoMapper;
using HS.Domain.Core.Contracts.ApplicationService;
using HS.Domain.Core.Dtos;
using HS.Domain.Core.Entities;
using HS.EndPoints.RazorPages.ShopUI.Model;
using HS.EndPoints.RazorPages.UI.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace HS.EndPoints.RazorPages.ShopUI.Areas.Admin.Pages
{

    [Authorize(Roles ="Admin")]
    public class UserManagementModel : PageModel
    {
        private readonly IApplicationUserApplicationService _applicationUserApplicationService;
        private readonly UserManager<ApplicationUser> _userManager;

        private readonly IMapper _mapper;
        public List<ApplicationUserViewModel> users;

        public UserManagementModel(UserManager<ApplicationUser> userManager,
            IMapper mapper,
            IApplicationUserApplicationService applicationUserApplicationService)
        {
            _userManager = userManager;
            _mapper = mapper;
            _applicationUserApplicationService = applicationUserApplicationService;
        }

        public async Task<IActionResult> OnPostActiveConfirmEmail(string email)
        {
            await  _applicationUserApplicationService.ActiveEmailConfirm(email);
            return LocalRedirect("/Admin/UserManagement");
        }

        public async Task<IActionResult> OnPostDeActiveConfirmEmail(string email)
        {
            await _applicationUserApplicationService.DeActiveEmailConfirm(email);
            return LocalRedirect("/Admin/UserManagement");
        }

        public async Task OnGet(CancellationToken cancellationToken )
        {
            users= _mapper.Map(await _applicationUserApplicationService.GetAll(cancellationToken), users);
        }

        public async Task<IActionResult> OnPostDelete(Guid id)
        {
            var user = await _userManager.Users.Where(x => x.Id == id).SingleAsync();
            await _userManager.DeleteAsync(user);
            return LocalRedirect("/Admin/UserManagement");
        }

        public async Task<IActionResult> OnPostCreate(RegisterViewModel model,CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                var result = await _applicationUserApplicationService.Create(_mapper.Map(model, new ApplicationUserDto()), cancellationToken);
                if (result.Succeeded)
                {
                    return LocalRedirect("/Admin/UserManagement");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, item.Description);
                        return default;
                    }
                    return LocalRedirect("/Admin/UserManagement");
                }
            }
            return LocalRedirect("/Admin/UserManagement");
        }
    }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Admin/Pages/ExpertComment.cshtml
@page
@model HS.EndPoints.RazorPages.UI.Areas.Admin.Pages.ExpertCommentModel
@{
       ViewData["Title"] = "کامنت های کارشناس";
}
<table class="table table-bordered table-striped table-hover" id="data-table">
    <tbody>
        @foreach(var comment in @Model.comments)
        {
        <tr> 
            <td >
               <lable>@comment.Body</lable>
            </td>
         </tr>
        }
    </tbody>
</table>

src/HS.EndPoints.RazorPages.ShopUI/Areas/Admin/Pages/OrderDetails.cshtml
@page
@using Framework.Utilities
@using HS.Domain.Core.Enums
@using System.Globalization
@model HS.EndPoints.RazorPages.UI.Areas.Admin.Pages.OrderDetailsModel
@{
    ViewData["Title"] = "مشخصات سفارش";
}
<label>جزئیات درخواست</label>
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>شناسه سفارش</th>
            <th>سفارش دهنده</th>
            <th>هوم سرویس</th>
            <th>تاریخ ثبت درخواست</th>
            <th>تاریخ اجرا </th>
            <th>ساعت اجرا </th>
            <th>وضعیت</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Order.Id</td>
            <td>@Model.Order.Customer.FirstName @Model.Order.Customer.LastName</td>
            <td>@Model.Order.HomeService.Name</td>
            <td>@Model.Order.RegisterDate.ToPersianString("yyyy/MM/dd")</td>
            <td>@Model.Order.DateOfExecution.ToPersianString("yyyy/MM/dd")</td>
            <td>@Model.Order.DateOfExecution.ToString("H:mm")</td>
            <td style="color:red">@Model.Order.Status.GetEnumDisplayName()</td>
        </tr>
    </tbody>
</table>


<hr>
<label>پیشنهاد ها</label>
<br />
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>شناسه پیشنهاد</th>
            <th>شناسه سفارش</th>
            <th>کارشناس</th>
            <th>قیمت پیشنهادی </th>
            <th>تاریخ پیشنهاد </th>
            <th>تاریخ اتمام کار</th>
            <th>عملیات</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.suggestions != null)
        {
            @foreach (var item in Model.suggestions)
            {
                @if (item.ExpertId == Model.UserId || User.IsInRole("Admin") || User.IsInRole("Customer"))
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.OrderId</td>
                        <td>@item.Expert.FirstName @item.Expert.LastName</td>
                        <td style="color:red">@item.SuggestedPrice.ToString("C", CultureInfo.CurrentCulture= new CultureInfo("fa-Ir",false))</td>
                        <td>@item.RegisterDate.ToPersianString("dddd, dd MMMM,yyyy")</td>
                        <td>@item.DurationOfWork.ToPersianString("dddd, dd MMMM,yyyy")</td>
                        <td>
                            <a data-bs-toggle="modal" data-bs-target="#SuggestionDetailsModal" HomeService="@item.Order.HomeService.Name" Order-Id="@item.Order.Id" Customer="@item.Expert.FirstName @item.Expert.LastName" Description="@item.Description" SuggId="@item.Id" asp-page-handler="Delete" class="btn btn-success curve">جزئیات پیشنهاد</a>
                        </td>
                    </tr>
                }
            }
        }

    </tbody>
</table>

<hr>
<div class="form-group">
    <label>توضیحات درخواست</label>
    <div class="input-group round">
        <span class="input-group-addon">
            <i class="icon-note"></i>
        </span>
        <textarea name="Description" class="form-control" rows="5">@Model.Order.Description</textarea>
    </div>
</div>
@if (@Model.Order.Status == OrderStatusEnum.Done && @User.IsInRole("Customer"))
{

    <hr>
      <form method="post" asp-page-handler="Comment">
      <input type="hidden" name="OrderId" value="@Model.Order.Id">
    <div class="form-group">
        <label style="color:red">شما میتوانید میزان رضایت خود را از عملکرد کارشناس در فرم زیر ثبت کنید</label>
        <div class="input-group round">
            <span class="input-group-addon">
                <i style="color:red" class="icon-note"></i>
            </span>
            <textarea name="Comment" class="form-control" rows="3"></textarea>
        </div>
        <br>
        <div style="float:left;">
            <button type="submit" class="btn btn-success curve">ثبت پیشنهاد<div class="paper-ripple"><div class="paper-ripple__background" style="opacity: 0.00616;"></div><div class="paper-ripple__waves"></div></div></button>
        </div>
    </div>
    </form>
}
<br />

<hr>
<label>تصاویر پیوست شده</label>
<center>
    <div class="col-sm-6">
        <table class="table table-bordered table-striped table-hover">
            <thead>
                <tr>
                    <th>تصاویر ثبت شده سفارش</th>
                    @if (@User.IsInRole("Admin"))
                    {
                        <th>عملیات</th>
                    }
                </tr>
            </thead>
            <tbody>
                @if (Model.suggestions != null)
                {

                    @foreach (var item in Model.orderFiles)
                    {
                        <tr>
                            <td>
                                <a href="/@item.Name" target="_blank">
                                    <img src="/@item.Name" class="img-circle" style="width:100px;height:100px" alt="Cinque Terre">
                                </a>
                            </td>
                            @if (@User.IsInRole("Admin"))
                            {
                                <td>
                                    <a data-bs-toggle="modal" Order-Id="@item.OrderId" image-Id="@item.Id"  data-bs-target="#ModalDelete" class="btn btn-danger curve">حذف تصویر</a>
                                </td>
                            }
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</center>
<hr>



<div class="modal fade" id="ModalDelete" tabindex="-1" role="dialog" aria-labelledby="DeleteLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createBrandLabel">حذف تصویر </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" asp-page-handler="DeleteImage">
                    <input type="hidden" name="imageId" id="imageId" />
                    <input type="hidden" name="orderIdDelete" id="orderIdDelete" />

                    <p>آیا از حذف تصویر اطمینان دارید ؟</p>
                    <hr />
                    <div style="float:left;">
                        @if (@User.IsInRole("Admin"))
                        {
                            <button type="submit" class="btn btn-danger curve">در صورت اطمینان از حذف کلیک کنید<div class="paper-ripple"><div class="paper-ripple__background" style="opacity: 0.00616;"></div><div class="paper-ripple__waves"></div></div></button>
                        }
                        <button type="button" class="btn btn-success curve " data-bs-dismiss="modal">بازگشت</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="SuggestionDetailsModal" tabindex="-1" role="dialog" aria-labelledby="SuggestionDetailsLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createBrandLabel">جزئیات پیشنهاد </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" asp-page-handler="Accept">
                    <input id="SuggId" name="SuggId" type="hidden" />
                    <div class="form-group">
                        <label>شماره سفارش</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="icon-key"></i>
                            </span>
                            <input name="OrderId" id="OrderId" type="text" class="form-control round" readonly>
                        </div>
                    </div>

                    <div class="form-group">
                        <label>کارشناس</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="icon-user"></i>
                            </span>
                            <input name="Customer" id="Customer" type="text" class="form-control round" disabled>
                        </div>
                    </div>

                    <div class="form-group">
                        <label>هوم سرویس سفارش</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="icon-wrench"></i>
                            </span>
                            <input name="HomeService" id="HomeService" type="text" class="form-control round" readonly>
                        </div>
                    </div>

                    <div class="form-group">
                        <label>توضیحات</label>
                        <div class="input-group round">
                            <span class="input-group-addon">
                                <i class="icon-note"></i>
                            </span>
                            <textarea id="Description" name="Description" class="form-control" rows="4" readonly></textarea>
                        </div>
                    </div>

                    <div style="float:left;">
                        <button type="button" class="btn btn-danger curve " data-bs-dismiss="modal">بازگشت</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section masterjs
    {
    <script>
        $(document).ready(function() {
            $(".table a").on("click", function() {
                var OrderId = $(this).attr("image-Id");
                $("#imageId").val(OrderId);
            });
        });
    </script>

    <script>
        $(document).ready(function() {
            $(".table a").on("click", function() {
                var SuggId = $(this).attr("SuggId");
                var OrderId = $(this).attr("Order-Id");
                var Description = $(this).attr("Description");
                var Customer = $(this).attr("Customer");
                var HomeService = $(this).attr("HomeService");
                $("#SuggId").val(SuggId);
                $("#Description").val(Description);
                $("#Customer").val(Customer);
                $("#HomeService").val(HomeService);
                $("#OrderId").val(OrderId);
                $("#orderIdDelete").val(OrderId);
            });
        });
    </script>
}