src/HS.EndPoints.RazorPages.ShopUI/Areas/Account/Pages/Forget.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HS.EndPoints.RazorPages.ShopUI.Areas.Account.Pages
{
    public class ForgetModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Account/Pages/Login.cshtml.cs
using AutoMapper;
using HS.Domain.Core.Contracts.ApplicationService;
using HS.Domain.Core.Contracts.Repository;
using HS.Domain.Core.Dtos;
using HS.Domain.Core.Entities;
using HS.EndPoints.RazorPages.ShopUI.Model;
using HS.Infrastructures.Database.SqlServer.Common;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.Entity;
using System.Web;

namespace HS.EndPoints.RazorPages.ShopUI.Areas.Account.Pages
{

    [Area("Account")]
    public class LoginModel : PageModel
    {

        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly SeedIdentityData _seedIdentityData;

        private readonly IApplicationUserApplicationService _applicationUserApplicationService;
        private readonly IMapper _mapper;

        public LoginModel(SignInManager<ApplicationUser> signInManager,
            SeedIdentityData seedIdentityData,
            IApplicationUserApplicationService applicationUserApplicationService,
            IMapper mapper)
        {
            _signInManager = signInManager;
            _seedIdentityData = seedIdentityData;
            _applicationUserApplicationService = applicationUserApplicationService;
            _mapper = mapper;
        }

        public async Task OnGet()
        {
             await _seedIdentityData.Inistialize();
        }

        public async Task OnPostLogout()
        {
            await _signInManager.SignOutAsync();
        }

        public async Task<IActionResult> OnPostLogin(LoginViewModel model,CancellationToken cancellationToken )
        {
           

            if (ModelState.IsValid)
            {
                var result =  await _applicationUserApplicationService.Login(_mapper.Map(model, new ApplicationUserDto()),cancellationToken);
                if (result.Succeeded)
                {
                    return LocalRedirect("/Admin/");
                }
                ModelState.AddModelError(string.Empty, "نام کاربری یا کلمه عبور اشتباه است *");
            }
            return default;
        }
        }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Account/Pages/Logout.cshtml.cs
using HS.Domain.Core.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HS.EndPoints.RazorPages.UI.Areas.Account.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<LogoutModel> _logger;

        public LogoutModel(SignInManager<ApplicationUser> signInManager, ILogger<LogoutModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        public async Task<IActionResult> OnPost(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                return RedirectToPage();
            }
        }
    }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Account/Pages/Register.cshtml.cs
using AutoMapper;
using HS.Domain.Core.Contracts.ApplicationService;
using HS.Domain.Core.Dtos;
using HS.Domain.Core.Entities;
using HS.EndPoints.RazorPages.ShopUI.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HS.EndPoints.RazorPages.ShopUI.Areas.Account.Pages
{
    [Area("Account")]
    public class RegisterModel : PageModel
    {
        private readonly IApplicationUserApplicationService _applicationUserApplicationService;
        private readonly IMapper _mapper;

        public RegisterModel(IMapper mapper,
            IApplicationUserApplicationService applicationUserApplicationService)
        {
            _mapper = mapper;
            _applicationUserApplicationService = applicationUserApplicationService;
        }

        public async Task<IActionResult> OnPostCreate(RegisterViewModel model,CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                var result = await _applicationUserApplicationService.Create(_mapper.Map(model, new ApplicationUserDto()), cancellationToken);
                if (result.Succeeded)
                {
                    return LocalRedirect("/Account/Login");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, item.Description);
                        return default;
                    }
                }
            }
            return default;
        }
    }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Account/Pages/Shared/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HS.EndPoints.RazorPages.ShopUI.Areas.Account.Pages.Shared
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Account/Pages/emailConfirmation.cshtml.cs
using HS.Domain.Core.Contracts.ApplicationService;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Web.Mvc;

namespace HS.EndPoints.RazorPages.UI.Areas.Account.Pages
{
    public class emailConfirmationModel : PageModel
    {
        private readonly IApplicationUserApplicationService _applicationUserApplicationService;
        public string Message;
        public emailConfirmationModel(IApplicationUserApplicationService applicationUserApplicationService)
        {
            _applicationUserApplicationService = applicationUserApplicationService;
        }

        public async Task OnGet(string confirmKey)
        {
           if(await _applicationUserApplicationService.confirmEmail(confirmKey))
                Message = "حساب کاربری شما با موفقیت فعال شد";
           else 
                Message = "کد فعال سازی نامعتبر می باشد";
        }
    }
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Account/Pages/Forget.cshtml
@page
@model HS.EndPoints.RazorPages.ShopUI.Areas.Account.Pages.ForgetModel
@{
    Layout = "_Layout";
    ViewBag.Title = "بازیابی رمز عبور";
}

<div class="col-md-12">
    <p class="text-center m-t-30 m-b-40">
        <i class="icon-lock-open border img-circle font-xxxlg p-20"></i>
    </p>
    <h2 class="text-center">بازیابی رمز عبور</h2>
    <hr>

    <form id="forget-form" method="POST" action="#">
        <div class="form-group">
            <label class="sr-only control-label" for="email">آدرس ایمیل</label>
            <div class="input-group round">
                <span class="input-group-addon">
                    <i class="icon-envelope"></i>
                </span>
                <input type="email" class="form-control round ltr text-left" id="email" name="email" required disabled>
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-info btn-round btn-block m-t-20" name="signup" value="Sign up" disabled>
                <i class="icon-envelope-letter"></i>
                ارسال ایمیل بازیابی
            </button>
        </div>
    </form>
</div>
@section Scripts{
<script src="/assets/js/pages/forget.js"></script>
}

<!-- END PAGE JAVASCRIPT -->

src/HS.EndPoints.RazorPages.ShopUI/Areas/Account/Pages/Login.cshtml
@page

@model HS.EndPoints.RazorPages.ShopUI.Areas.Account.Pages.LoginModel
@{
    Layout = "_Layout";
    ViewBag.Title = "ورود به سایت";

}
<div class="col-md-12">
    <p class="text-center m-t-30 m-b-40">
        <i class="icon-user-following border img-circle font-xxxlg p-20"></i>
    </p>

    <h2 class="text-center m-b-20">ورود به سایت</h2>
    <form id="form" class="m-t-30 m-b-30" role="form" asp-page-handler="Login" method="post">
        <div style="text-align: center;" asp-validation-summary="All" class="text-danger"></div>
        @Html.Hidden("returnUrl",@Request.QueryString)
        <div class="form-group">
            <label for="email" class="sr-only">آدرس ایمیل</label>
            <div class="input-group round">
                <span class="input-group-addon">
                    <i class="icon-envelope"></i>
                </span>
                <input id="email" class="form-control ltr text-left" type="email" name="email" required>
            </div><!-- /.input-group -->
        </div><!-- /.form-group -->


        <div class="form-group">
            <label for="password" class="sr-only">کلمه عبور</label>
            <div class="input-group round">
                <span class="input-group-addon">
                    <i class="icon-key"></i>
                </span>
                <input id="password" name="password" class="form-control ltr text-left" type="password" minlength="5" required>
            </div><!-- /.input-group -->
        </div><!-- /.form-group -->
        <p>

        </p>
        <br>
        <button type="submit" class="btn btn-info btn-round btn-block">
            <i class="icon-paper-plane font-lg"></i>
            ورود به سایت
        </button>
    </form>
    <hr class="m-b-30">
    <a asp-page="/Forget" class="btn btn-default btn-round btn-block m-b-10">
        <i class="icon-refresh font-lg"></i>
        بازیابی رمز  عبور
    </a>
    <a asp-page="/Register" class="btn btn-default btn-round btn-block">
        <i class="icon-user-follow font-lg"></i>
        حساب ندارید، ثبت نام کنید!
    </a>
</div>

@section Scripts{
    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <recaptcha-script jquery-validation="false" />
    <script src="/assets/js/pages/login.js"></script>
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Account/Pages/Logout.cshtml
@page
@model HS.EndPoints.RazorPages.UI.Areas.Account.Pages.LogoutModel
@{
    ViewData["Title"] = "خروج از سایت";
}
<header>
    <h1>@ViewData["Title"]</h1>
    @{
        if (User.Identity.IsAuthenticated)
        {
            <form class="form-inline"  asp-page="/Account/Logout" asp-route-returnUrl="@Url.Page("/", new { area = "" })" method="post">
                <button type="submit" class="nav-link btn btn-link text-dark">برای خروج از سایت کلیک روی این عبارت کنید</button>
            </form>
        }
        else
        {
            <a href="/Account/Login/">برای ورود به سایت کلیک کنید</a>
        }
    }
</header>

src/HS.EndPoints.RazorPages.ShopUI/Areas/Account/Pages/Register.cshtml
@page
@model HS.EndPoints.RazorPages.ShopUI.Areas.Account.Pages.RegisterModel
@{
    Layout = "_Layout";
    ViewBag.Title = "ثبت نام در سایت";
}

<div class="col-md-12">
    <p class="text-center m-t-30 m-b-40">
        <i class="icon-user-following border img-circle font-xxxlg p-20"></i>
    </p>
    <h2 class="text-center m-b-20">ایجاد حساب کاربری</h2>
    <hr>

    <form id="form" class="m-t-30 m-b-30" role="form" asp-page-handler="Create" method="post">
        <div asp-validation-summary="All" class="text-danger"> </div>

        <div class="form-group">
            <label for="email" class="sr-only">آدرس ایمیل</label>
            <div class="input-group round">
                <span class="input-group-addon">
                    <i class="icon-envelope"></i>
                </span>
                <input id="email" class="form-control  ltr text-left" type="email" name="email" required>
            </div><!-- /.input-group -->
        </div><!-- /.form-group -->
        <div class="form-group">
            <label for="password" class="sr-only">کلمه عبور</label>
            <div class="input-group round">
                <span class="input-group-addon">
                    <i class="icon-key"></i>
                </span>
                <input type="password" class="form-control round ltr text-left" id="password" name="password" required>
                <span asp-validation="password"></span>

            </div><!-- /.input-group-->
        </div><!-- /.form-group -->
        <div class="form-group">
            <label for="password" class="sr-only">تکرار کلمه عبور</label>

            <div class="input-group round">
                <span class="input-group-addon">
                    <i class="icon-key"></i>
                </span>
                <input type="password" class="form-control round  ltr text-left" id="ConfirmPassword" name="ConfirmPassword" required>
                <span asp-validation="ConfirmPassword"></span>

            </div><!-- /.input-group-->
        </div><!-- /.form-group -->

         <div class="form-group">
            <label for="email" class="sr-only">نوع کاربر</label>
            <div class="input-group round">
                <span class="input-group-addon">
                    <i class="icon-envelope"></i>
                </span>
                <select class="form-control" name="Role">
                    <option value="Customer" >مشتری</option>
                    <option value="Expert">کارشناس</option>
                </select>
            </div><!-- /.input-group -->
        </div><!-- /.form-group -->

        <div class="form-group">
            <button type="submit" class="btn btn-info btn-round btn-block" name="signup" value="Sign up">
                <i class="icon-check"></i>
                ثبت نام
            </button>
        </div><!-- /.form-group -->
    </form>

    <hr class="m-b-30">
    <a asp-page="/Forget" class="btn btn-default btn-round btn-block m-b-10">
        <i class="icon-refresh font-lg"></i>
        بازیابی رمز  عبور
    </a>
    <a asp-page="/Login" class="btn btn-default btn-round btn-block">
        <i class="icon-user-follow font-lg"></i>
        ثبت نام کرده اید؟ وارد شوید!
    </a>
</div>
@section Scripts{
    <script src="/assets/js/pages/register.js"></script>
}

src/HS.EndPoints.RazorPages.ShopUI/Areas/Account/Pages/emailConfirmation.cshtml
@page
@model HS.EndPoints.RazorPages.UI.Areas.Account.Pages.emailConfirmationModel
@{
        Layout = "_Layout";
    ViewBag.Title = "بازیابی رمز عبور";
}


<div class="text-center">
    <h3 style="color:red" >@Model.Message</h3>
    <hr>
    <a style="color:black" asp-page="./Profile">برای ورود به سایت کلیک کنید</a>
</div>